---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes 
  
  - name: install apache2 package 
    yum:
      name: httpd
 
  - name: start httpd
    service: 
      name: httpd
      state: started
      enabled: true
